// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxyskswnktcyhnsnkvul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4eXNrc3dua3RjeWhuc25rdnVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDAyNzMsImV4cCI6MjA2MzE3NjI3M30.7nou73w-xQFqxICzcfL_7yxx4SxPHsv_RMj3yXQbyds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);